services:
  main:
    build: packages/main
    ports:
      - "3000:80"
  counter:
    build: packages/counter
  mobx:
    build: packages/cra-ts-mobx
  server:
    build: packages/server
    environment:
      - USE_JWT_AUTH=${USE_JWT_AUTH} 
      - TOKEN_SECRET=${TOKEN_SECRET}
