services:
  main:
    build: packages/main
    ports:
      - "8080:80"
  counter:
    build: packages/counter
    ports:
      - "8081:80"
  mobx:
    build: packages/cra-ts-mobx
    ports:
      - "8082:80"
  server:
    build: packages/server
    ports:
      - "7000:7000"